version: "2.1"
services:
  frontend:
    build: .
    command: python run-app.py
    ports: 
      - "3001:3001"
    links:
      - datastore

  datastore:
    image: mongo:3.0.2
    ports: 
      - "27017:27017"
