version: "2.1"
services:
  booklist-ms:
    build: .
    command: python run-app.py
    ports: 
      - "3001:3001"
    links:
      - booklist-db

  booklist-db:
    image: mongo:3.0.2
    ports: 
      - "27017:27017"
